# Generated by Django 6.0.5 on 2026-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Reclutador o Empresa"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                (
                    "mensaje",
                    models.TextField(verbose_name="Mensaje / Detalle de la vacante"),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Envío"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfertaTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Cargo"),
                ),
                (
                    "empresa",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Empresa"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción del Cargo")),
                (
                    "ubicacion",
                    models.CharField(max_length=100, verbose_name="Ubicación / Ciudad"),
                ),
                (
                    "salario",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Salario (Opcional)",
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Publicación"
                    ),
                ),
            ],
        ),
    ]
